import type { TradeFlowData } from "@/lib/types"

export const demoCredentials = {
  email: "demo@tradeflow.app",
  password: "password123",
} as const

export const tradeFlowData: TradeFlowData = {
  metrics: [
    {
      label: "Open leads",
      value: "24",
      context: "$184K estimated pipeline",
      delta: "+8% this month",
      trend: "up",
    },
    {
      label: "Active jobs",
      value: "11",
      context: "4 crews booked",
      delta: "+2 this week",
      trend: "up",
    },
    {
      label: "AR outstanding",
      value: "$42,850",
      context: "6 invoices awaiting payment",
      delta: "-14% vs last month",
      trend: "down",
    },
    {
      label: "Close rate",
      value: "38%",
      context: "Estimate-to-job conversion",
      delta: "+4 points",
      trend: "up",
    },
  ],
  revenue: [
    { month: "Jan", revenue: 42000, collected: 38100 },
    { month: "Feb", revenue: 51000, collected: 46750 },
    { month: "Mar", revenue: 47800, collected: 43900 },
    { month: "Apr", revenue: 62000, collected: 58150 },
    { month: "May", revenue: 73500, collected: 68800 },
    { month: "Jun", revenue: 80100, collected: 75225 },
  ],
  pipeline: [
    { stage: "New inquiry", count: 7, value: 84200 },
    { stage: "Site visit scheduled", count: 5, value: 116400 },
    { stage: "Estimate sent", count: 6, value: 149800 },
    { stage: "Awaiting deposit", count: 3, value: 63100 },
    { stage: "Won", count: 3, value: 90400 },
  ],
  leads: [
    {
      id: "lead-101",
      customerName: "Jordan Ramirez",
      projectType: "Roof replacement",
      stage: "Estimate sent",
      status: "Hot",
      source: "Google Ads",
      phone: "(312) 555-0184",
      email: "jordan.ramirez@example.com",
      address: "1840 W School St, Chicago, IL",
      budget: 18000,
      estimatedValue: 21400,
      timeline: "2-4 weeks",
      assignedTo: "Maya Chen",
      lastContacted: "2026-06-18",
      nextAction: "Follow up on estimate and shingle upgrade",
      createdAt: "2026-06-05",
      notes: [
        "Storm damage claim is already filed.",
        "Customer is comparing Owens Corning vs GAF upgrade.",
      ],
    },
    {
      id: "lead-102",
      customerName: "Avery Patel",
      company: "Patel Family Properties",
      projectType: "Kitchen remodel",
      stage: "Site visit scheduled",
      status: "Warm",
      source: "Referral",
      phone: "(773) 555-0120",
      email: "avery.patel@example.com",
      address: "910 N Wolcott Ave, Chicago, IL",
      budget: 55000,
      estimatedValue: 62400,
      timeline: "Start in August",
      assignedTo: "Leo Barnes",
      lastContacted: "2026-06-19",
      nextAction: "Measure cabinetry and appliance rough-ins",
      createdAt: "2026-06-11",
      notes: [
        "Client wants custom white oak island.",
        "Permit likely needed for wall relocation.",
      ],
    },
    {
      id: "lead-103",
      customerName: "Naomi Brooks",
      projectType: "HVAC install",
      stage: "Awaiting deposit",
      status: "Hot",
      source: "Website",
      phone: "(708) 555-0168",
      email: "naomi.brooks@example.com",
      address: "4417 Harvey Ave, Berwyn, IL",
      budget: 12400,
      estimatedValue: 13850,
      timeline: "ASAP before heat wave",
      assignedTo: "Maya Chen",
      lastContacted: "2026-06-20",
      nextAction: "Collect signed proposal and 40% deposit",
      createdAt: "2026-06-09",
      notes: [
        "Requested high-efficiency variable speed system.",
        "Electrical panel has adequate capacity.",
      ],
    },
    {
      id: "lead-104",
      customerName: "Chris Odom",
      projectType: "Bathroom renovation",
      stage: "New inquiry",
      status: "Cold",
      source: "Facebook",
      phone: "(630) 555-0107",
      email: "chris.odom@example.com",
      address: "128 W Illinois St, Wheaton, IL",
      budget: 22000,
      estimatedValue: 24750,
      timeline: "Fall project",
      assignedTo: "Leo Barnes",
      lastContacted: "2026-06-15",
      nextAction: "Call to qualify tile and plumbing scope",
      createdAt: "2026-06-14",
      notes: [
        "Wants heated floors if budget allows.",
      ],
    },
    {
      id: "lead-105",
      customerName: "Sofia Martinez",
      projectType: "Deck rebuild",
      stage: "Won",
      status: "Hot",
      source: "Yard sign",
      phone: "(847) 555-0149",
      email: "sofia.martinez@example.com",
      address: "775 Maple Ave, Evanston, IL",
      budget: 32000,
      estimatedValue: 30150,
      timeline: "Start after July 4",
      assignedTo: "Maya Chen",
      lastContacted: "2026-06-17",
      nextAction: "Move into production schedule",
      createdAt: "2026-05-29",
      notes: [
        "Composite decking selected with black aluminum rails.",
      ],
    },
    {
      id: "lead-106",
      customerName: "Trevor Hall",
      projectType: "Window replacement",
      stage: "Estimate sent",
      status: "Warm",
      source: "Home show",
      phone: "(815) 555-0136",
      email: "trevor.hall@example.com",
      address: "300 E Liberty Dr, Naperville, IL",
      budget: 27500,
      estimatedValue: 29100,
      timeline: "Before September",
      assignedTo: "Leo Barnes",
      lastContacted: "2026-06-16",
      nextAction: "Price alternate fiberglass package",
      createdAt: "2026-06-03",
      notes: [
        "Main pain point is street noise in front bedrooms.",
      ],
    },
  ],
  jobs: [
    {
      id: "job-201",
      leadId: "lead-105",
      title: "Martinez backyard deck rebuild",
      clientName: "Sofia Martinez",
      service: "Deck rebuild",
      status: "Awaiting deposit",
      address: "775 Maple Ave, Evanston, IL",
      startDate: "2026-07-08",
      targetDate: "2026-07-28",
      contractValue: 30150,
      depositStatus: "Awaiting deposit",
      invoiceStatus: "Sent",
      progress: 18,
      priority: "High",
      permit: "Submitted to Evanston zoning",
      projectManager: "Maya Chen",
      crew: ["Luis", "Cameron", "Darius"],
      description:
        "Demo existing treated lumber deck and rebuild with composite boards, fascia wrap, and black aluminum guard rail.",
      milestones: [
        { label: "Permit submitted", completed: true },
        { label: "Deposit received", completed: false },
        { label: "Material order placed", completed: false },
        { label: "Framing inspection", completed: false },
      ],
    },
    {
      id: "job-202",
      leadId: "lead-103",
      title: "Brooks HVAC install",
      clientName: "Naomi Brooks",
      service: "HVAC install",
      status: "Permit pending",
      address: "4417 Harvey Ave, Berwyn, IL",
      startDate: "2026-06-27",
      targetDate: "2026-06-29",
      contractValue: 13850,
      depositStatus: "Deposit received",
      invoiceStatus: "Draft",
      progress: 46,
      priority: "High",
      permit: "Permit pending with Berwyn mechanical department",
      projectManager: "Maya Chen",
      crew: ["Emilio", "Kai"],
      description:
        "Install 96% AFUE furnace and 18 SEER condenser with new lineset, pad, disconnect, and smart thermostat setup.",
      milestones: [
        { label: "Deposit received", completed: true },
        { label: "Equipment reserved", completed: true },
        { label: "Permit approval", completed: false },
        { label: "Final startup", completed: false },
      ],
    },
    {
      id: "job-203",
      leadId: "lead-101",
      title: "Ramirez roof replacement",
      clientName: "Jordan Ramirez",
      service: "Roof replacement",
      status: "In progress",
      address: "1840 W School St, Chicago, IL",
      startDate: "2026-06-21",
      targetDate: "2026-06-24",
      contractValue: 21400,
      depositStatus: "Deposit received",
      invoiceStatus: "Sent",
      progress: 68,
      priority: "High",
      permit: "No permit required",
      projectManager: "Leo Barnes",
      crew: ["Mateo", "Julian", "Rico", "Ben"],
      description:
        "Full tear-off and replacement with ice shield, synthetic underlayment, architectural shingles, ridge vent, and chimney flashing.",
      milestones: [
        { label: "Materials delivered", completed: true },
        { label: "Tear-off complete", completed: true },
        { label: "Install complete", completed: false },
        { label: "Punch list closeout", completed: false },
      ],
    },
    {
      id: "job-204",
      title: "Patel kitchen remodel",
      clientName: "Avery Patel",
      service: "Kitchen remodel",
      status: "Change order",
      address: "910 N Wolcott Ave, Chicago, IL",
      startDate: "2026-08-04",
      targetDate: "2026-09-19",
      contractValue: 62400,
      depositStatus: "Deposit received",
      invoiceStatus: "Paid",
      progress: 52,
      priority: "Medium",
      permit: "Permit pending for wall relocation",
      projectManager: "Leo Barnes",
      crew: ["Hector", "Ari", "Cam"],
      description:
        "Complete kitchen gut renovation including cabinetry, quartz tops, appliance package, recessed lighting, and pantry build-out.",
      milestones: [
        { label: "Demo complete", completed: true },
        { label: "Electrical rough-in", completed: true },
        { label: "Cabinet install", completed: false },
        { label: "Countertop template", completed: false },
      ],
    },
  ],
  invoices: [
    {
      id: "inv-301",
      jobId: "job-203",
      clientName: "Jordan Ramirez",
      amount: 12840,
      status: "Sent",
      issuedAt: "2026-06-19",
      dueAt: "2026-06-26",
      description: "Roof replacement progress draw",
    },
    {
      id: "inv-302",
      jobId: "job-202",
      clientName: "Naomi Brooks",
      amount: 5540,
      status: "Draft",
      issuedAt: "2026-06-20",
      dueAt: "2026-06-27",
      description: "HVAC install final balance",
    },
    {
      id: "inv-303",
      jobId: "job-204",
      clientName: "Avery Patel",
      amount: 24960,
      status: "Paid",
      issuedAt: "2026-06-01",
      dueAt: "2026-06-08",
      description: "Kitchen remodel phase 2 draw",
    },
    {
      id: "inv-304",
      jobId: "job-201",
      clientName: "Sofia Martinez",
      amount: 12060,
      status: "Overdue",
      issuedAt: "2026-06-07",
      dueAt: "2026-06-14",
      description: "Deck rebuild deposit invoice",
    },
  ],
  activity: [
    {
      id: "act-401",
      type: "invoice",
      title: "Invoice overdue",
      description: "Deck rebuild deposit is 6 days overdue.",
      actor: "Accounting",
      timestamp: "2026-06-20T08:15:00Z",
    },
    {
      id: "act-402",
      type: "job",
      title: "Permit pending",
      description: "Brooks HVAC install is waiting on mechanical approval.",
      actor: "Maya Chen",
      timestamp: "2026-06-20T07:10:00Z",
    },
    {
      id: "act-403",
      type: "lead",
      title: "Estimate opened",
      description: "Jordan Ramirez viewed the roof estimate twice this morning.",
      actor: "System",
      timestamp: "2026-06-20T06:40:00Z",
    },
    {
      id: "act-404",
      type: "estimate",
      title: "Site visit booked",
      description: "Kitchen remodel walkthrough confirmed for June 24 at 2:30 PM.",
      actor: "Leo Barnes",
      timestamp: "2026-06-19T21:05:00Z",
    },
  ],
  team: [
    { id: "tm-1", name: "Maya Chen", role: "Project Manager", initials: "MC" },
    { id: "tm-2", name: "Leo Barnes", role: "Estimator", initials: "LB" },
    { id: "tm-3", name: "Nina Flores", role: "Office Manager", initials: "NF" },
  ],
  settings: {
    companyName: "TradeFlow Contractors",
    ownerName: "Edward Reed",
    officeEmail: "office@tradeflow.app",
    officePhone: "(312) 555-0111",
    license: "IL GC LIC 24109-77",
    defaultTerms:
      "50% deposit due at contract signing. Remaining balance invoiced at substantial completion unless otherwise noted in proposal.",
    serviceArea: ["Chicago", "Evanston", "Berwyn", "Naperville", "Wheaton"],
  },
}
